---
title: "Testing_3"
author: "Austin Reed"
date: "02/09/2020"
output: html_document
---

#This is throw away code just to test some things

Initial set up
```{r, message=FALSE}
library(ggplot2)
library(plyr)
library(dplyr)

#Bioc Packages
library(scran)
library(scater)

sce <- readRDS("../data/sce_toy2.rds")

#also add in Alecia's cluster names found previously
Clusters <- c("C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12", "C13", "C14","C15")
Classes <- c("Luminal_HMC", "Luminal_HMC", "Luminal_HMC", "Luminal_HMC", "Luminal_HMC", "Immune", "Luminal_HMC", "Endothelial",  "Vascular_accessory", "Luminal_LP","Basal", "Luminal_HR", "Immune",  "Immune", "Fibroblast")
colData(sce)$Classes <- mapvalues(colData(sce)$GraphClusters, Clusters, Classes)

row.names(sce) <- rowData(sce)$Symbol

sce

head(colData(sce))
```


Selecting out the sections
```{r}
#as the previous analysis didn't appear to show much significant heterogeneity between the RB and HMC cells within the Milk bigcluster I will not subsection them for this analysis

sce.LumHMC <- sce[,colData(sce)$Classes == 'Luminal_HMC']
sce.LP <- sce[,colData(sce)$Classes == 'Luminal_LP']
sce.HR <- sce[,colData(sce)$Classes == 'Luminal_HR']

Barcodes.LumHMC <- sample(sce.LumHMC$Barcode,300)
Barcodes.LP <- sample(sce.LP$Barcode,300)
Barcodes.HR <- sample(sce.HR$Barcode,300)
Barcodes <- c(Barcodes.LumHMC,Barcodes.LP,Barcodes.HR)

sce.sub <- sce[,Barcodes]
sce.sub
table(sce.sub$Classes)
```


